### ISSUE TITLE
Remove `pnpm` requirements

### ISSUE THREAD

**Issue by wSedlacek** [radarsu/ts-options-defaults#1]
It appears that `pnpm` is requires to use this package and by extension `ts-import`, it would be nice if this wasn't the case.

```
error nx-tools/node_modules/ts-options-defaults: Command failed.
Exit code: 1
Command: npx only-allow pnpm
Arguments: 
Directory: nx-tools/node_modules/ts-options-defaults
Output:
npx: installed 26 in 2.143s
Opening `/dev/tty` failed (6): Device not configured
╔═════════════════════════════════════════════════════════════╗
║                                                             ║
║   Use "pnpm install" for installation in this project.      ║
║                                                             ║
║   If you don't have pnpm, install it via "npm i -g pnpm".   ║
```

**Comment by radarsu** [comment]
I'll publish new version with a fix as soon as possible.

For now you could remove:
```
    "scripts": {
        "preinstall": "npx only-allow pnpm"
    }
```
From `node_modules/ts-options-defaults/package.json` and `node_modules/ts-import` - let me know if without preinstall script there are no further problems.

EDIT:
I've published prerelease version ts-import@0.0.34-4 which uses fixed ts-options-defaults@0.0.34-3. Let me know if it works. Later on I'll do some tests to ensure library works with all major package managers: `npm`, `yarn`, and `pnpm`.
Just to avoid confusion - changes are not yet pushed to github (just to npm).
